Added Action to execute on Ubuntu

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -69,6 +69,13 @@ jobs:
           while (Test-Path Alias:curl) {Remove-Item Alias:curl} #remove the alias binding from curl to Invoke-WebRequest
           curl "-u${{secrets.NEXUSAUTHENTICATION}}" -T bin\LemonTree.Pipeline.Tools.ModelCheck.exe $targetUrl
       
+     - name: Archive Session Files
+       uses: actions/upload-artifact@v3
+       with:
+          name: LemonTree.Pipeline.Tools.Bin
+          path: "bin/*.*"
+          retention-days: 2
+
     #  - name: Upload LemonTree.Pipeline.Tools.GetModelRoots.exe
     #    if: github.ref == 'refs/heads/main'
     #    run: |
@@ -190,3 +197,48 @@ jobs:
           {
             exit steps.modelcheck.outputs.modelcheckExitCode
           }
+
+  TestOnUbuntu:
+    runs-on: ubuntu-latest
+    needs: build
+    timeout-minutes: 15
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          lfs: true
+          fetch-depth: 0
+
+      - name: Check out repository code
+        uses: actions/checkout@v3
+      
+      - name: Download a single artifact
+        uses: actions/download-artifact@v3
+        with:
+           name: LemonTree.Pipeline.Tools.Bin
+      
+      - name: Unzip LemonTree.Pipeline.Tools.Bin
+        run: |
+          Expand-Archive LemonTree.Pipeline.Tools.Bin.zip -DestinationPath .\bin\ -Force
+      
+      - name: Run LemonTree Check Tool SqLite
+        id: modelcheckSqlite
+        run: |
+               echo "starting validation"
+               dotnet .\bin\LemonTree.Pipeline.Tools.ModelCheck  --model "${{env.ModelNameSqLite}}" --out ".\output.md" 
+               type "output.md"
+     
+               echo "finished validation with $LASTEXITCODE"
+     
+               #  Exit codes of LemonTree.Pipeline.Tools.ModelCheck.exe:
+               #  * -2 = other runtime exception occurred
+               #  * -1 = CLI argument parsing error occurred
+               #  *  0 = model is valid (no error, no warning, no runtime exception)
+               #  *  1 = model has at least one warning (only if --FailOnWarnings or --FailOnErrors)
+               #  *  2 = model has at least one error  (only if --FailOnErrors)
+     
+               $Message = "output.md"
+     
+               echo "modelcheckExitCode=$LASTEXITCODE" >> $env:GITHUB_OUTPUT
+           
+               #for now never stop 
+               exit $LASTEXITCODE
