LemonTree.Pipeline.Tools.ModelCheck (#9)
* Introduced an Assembly that stores shared functionality and added a new project for modelcheck

* two checks implemented

Audit Check added

Audit Check

Update Program.cs

Add User Security Check

Action Update

run LT check after checkin

Improved Actions

Added Check for VCS enabled packages

Update Program.cs

Updated Issue.Level's

Added ExtDoc Check

Review Remarks resolved

cleaned up

Refactoring

Some more clean up

Added Size Check

Added Strip and Compact

Finished Model SIze Output

changed to x86

Interop.JRO.dll

added as content

Update LemonTree.Pipeline.Tools.csproj

changed reference

Try to install MS Access

Next Try

Update Build.yml

Update Build.yml

Update Build.yml

Update Build.yml

Late binding

Update LemonTree.Pipeline.Tools.csproj

removed adodb

Update LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.csproj

cahnged to x86

trying to make everything x86

changed to anycpu

changed back

Update LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.csproj

Update LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.csproj

disabled remove prerendered diagrams

set it hardcore to x86

removed ilmerge

removed ilmerge

readded Ilmerge

worked on project typtes

Update ModelAccess.cs

more error reporting

Update ModelAccess.cs

trying next db engine

Debug message

switched to Jet

removed access install

* Added checks for t_image entries

* Check if Audit is enabled

* Output to Console

* Fail on Errors and Warnings Option

* Update Build.yml

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -3,6 +3,7 @@ name: Build
 on: [push]
 env:
   NexusArtifactRepo: https://nexus.lieberlieber.com/repository/lemontree-pipeline-tools
+  ModelName: src\models\pwc.eapx
   
 jobs:
   build:
@@ -31,13 +32,111 @@ jobs:
           $targetUrl = "${{env.NexusArtifactRepo}}/LemonTree.Pipeline.Tools.SetFilterInSessionFile.exe"
           echo "Uploading 	LemonTree.Pipeline.Tools.SetFilterInSessionFile.exe to Nexus: $targetUrl"
           while (Test-Path Alias:curl) {Remove-Item Alias:curl} #remove the alias binding from curl to Invoke-WebRequest
-          curl "-u${{secrets.NEXUSAUTHENTICATION}}" -T src\LemonTree.Pipeline.Tools.SetFilterInSessionFile\bin\Release\LemonTree.Pipeline.Tools.SetFilterInSessionFile.exe $targetUrl
+          curl "-u${{secrets.NEXUSAUTHENTICATION}}" -T bin\LemonTree.Pipeline.Tools.SetFilterInSessionFile.exe $targetUrl
           
      - name: Upload LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.exe
        if: github.ref == 'refs/heads/main'
        run: |
           $targetUrl = "${{env.NexusArtifactRepo}}/LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.exe"
-          echo "Uploading 	LemonTree.Pipeline.Tools.SetFilterInSessionFile.exe to Nexus: $targetUrl"
+          echo "Uploading 	LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.exeto Nexus: $targetUrl"
           while (Test-Path Alias:curl) {Remove-Item Alias:curl} #remove the alias binding from curl to Invoke-WebRequest
-          curl "-u${{secrets.NEXUSAUTHENTICATION}}" -T src\LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams\bin\Release\LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.exe $targetUrl
+          curl "-u${{secrets.NEXUSAUTHENTICATION}}" -T bin\LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.exe $targetUrl
+     
+     - name: Upload LemonTree.Pipeline.Tools.ModelCheck.exe
+       if: github.ref == 'refs/heads/main'
+       run: |
+          $targetUrl = "${{env.NexusArtifactRepo}}/LemonTree.Pipeline.Tools.ModelCheck.exe"
+          echo "Uploading 	LemonTree.Pipeline.Tools.ModelCheck.exe to Nexus: $targetUrl"
+          while (Test-Path Alias:curl) {Remove-Item Alias:curl} #remove the alias binding from curl to Invoke-WebRequest
+          curl "-u${{secrets.NEXUSAUTHENTICATION}}" -T bin\LemonTree.Pipeline.Tools.ModelCheck.exe $targetUrl
       
+     - name: Run LemonTree Check Tool
+       id: modelcheck
+       run: |
+          echo "starting validation"
+          .\bin\LemonTree.Pipeline.Tools.ModelCheck.exe  --model "${{env.ModelName}}" --out ".\output.md" --FailOnErrors 
+          type "output.md"
+
+          echo "finished validation with $LASTEXITCODE"
+
+          #  Exit codes of LemonTree.Pipeline.Tools.ModelCheck.exe:
+          #  * -2 = other runtime exception occurred
+          #  * -1 = CLI argument parsing error occurred
+          #  *  0 = model is valid (no error, no warning, no runtime exception)
+          #  *  1 = model has at least one warning (only if --FailOnWarnings or --FailOnErrors)
+          #  *  2 = model has at least one error  (only if --FailOnErrors)
+
+          $Message = "output.md"
+
+          echo "::set-output name=modelcheckExitCode::$($LASTEXITCODE)"
+      
+          #for now never stop 
+          exit 0
+
+     - name: Extract branch name
+       shell: bash
+       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+       id: extract_branch
+
+     - name: Find Pull Request
+       uses: juliangruber/find-pull-request-action@v1
+       id: find-pull-request
+       with:
+           branch: ${{ steps.extract_branch.outputs.branch }}
+
+     - name: Read output.md
+       if: ${{ steps.find-pull-request.outputs.number > 0}} #only makes sense if we have a PR for the branch
+       id: package
+       uses: juliangruber/read-file-action@v1
+       with:
+            path: .\output.md
+
+     - name: Create PR comment
+       if: ${{ steps.find-pull-request.outputs.number > 0}} #only makes sense if we have a PR for the branch
+       uses: actions/github-script@v5
+       with:
+          script: |
+            await github.rest.issues.createComment({
+              issue_number: ${{ steps.find-pull-request.outputs.number }},
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `${{ steps.package.outputs.content }}`
+            })
+
+     - name: evaulate Exit Code
+       run: |
+          echo "set job failed on ..."
+          echo "Current Exit Code ${{ steps.modelcheck.outputs.modelcheckExitCode }}"
+
+          #  Exit codes of LemonTree.Pipeline.Tools.ModelCheck.exe:
+          #  * -2 = other runtime exception occurred
+          #  * -1 = CLI argument parsing error occurred
+          #  *  0 = model is valid (no error, no warning, no runtime exception)
+          #  *  1 = model has at least one warning (only if --FailOnWarnings or --FailOnErrors)
+          #  *  2 = model has at least one error  (only if --FailOnErrors)
+
+          if (${{ steps.modelcheck.outputs.modelcheckExitCode }} -eq 1)
+          {
+            #fail on warning
+            Echo "model has at least one warning"
+            #fail on warning
+            #exit 3
+            #ignore warning
+            exit 0
+          }
+          elseif (${{ steps.modelcheck.outputs.modelcheckExitCode }} -eq 2)
+          {
+              #fail on Error
+              echo "model has at least one error"
+              exit 2
+          }
+          elseif (${{ steps.modelcheck.outputs.modelcheckExitCode }} -eq 0)
+          {
+            #brilliant model
+            Echo "modelcheck is passed"
+            exit 0
+          }
+          else
+          {
+            exit steps.modelcheck.outputs.modelcheckExitCode
+          }
